export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen w-full max-w-4xl px-4 py-24 text-foreground md:px-6">
      <h1 className="font-display text-4xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-4 text-sm text-muted-foreground">Last updated: April 2026</p>
      <section className="mt-10 space-y-4 text-base leading-relaxed text-muted-foreground">
        <p>
          By using this website and BOS services, you agree to use the platform lawfully and not
          misuse the service or interfere with operations.
        </p>
        <p>
          BOS provides software tools and AI receptionist capabilities on an as-is basis. Service
          features may change over time as we improve reliability and performance.
        </p>
        <p>
          You are responsible for maintaining accurate business information and for reviewing any
          bookings or communications generated by your configured workflows.
        </p>
        <p>
          For terms enquiries, contact us at{" "}
          <a className="text-primary hover:underline" href="mailto:jayson@chatos.com.au">
            jayson@chatos.com.au
          </a>
          .
        </p>
      </section>
    </main>
  )
}
